---
- name: Create application directories
  become: yes
  file: path={{ item }} state=directory owner=vagrant group=vagrant mode=0745 recurse=yes
  with_items:
    - "{{ api.doc_root }}"
    - "{{ front.doc_root }}"

- name: Create the "node" user, under which the API application will run
  become: yes
  user: name=node

- name: Ensure Forever is installed
  npm: name=forever global=yes

- name: Configure the API application to start at the system boot
  become: yes
  template: src=app/api-run.conf.tpl dest=/etc/init/api-run.conf mode=0644
