---
- name: Create application directories
  become: yes
  file: path={{ item }} state=directory owner=vagrant group=vagrant mode=0745 recurse=yes
  with_items:
    - "{{ api.doc_root }}"
    - "{{ front.doc_root }}"

- name: Install Gulp, Bower and Forever
  npm: name={{ item }} global=yes
  with_items:
    - gulp-cli
    - bower
    - forever

- name: Configure the API application to start at the system boot
  become: yes
  template: src=app/api-run.conf.tpl dest=/etc/init/api-run.conf mode=0644
