---
- name: Configure the virtual hosts for the front & API applications
  become: yes
  template: src=nginx/{{ item }}.tpl dest=/etc/nginx/sites-available/{{ item }}
  with_items:
    - front
    - api

- name: Enabled the configured virtual hosts
  become: yes
  file: src=/etc/nginx/sites-available/{{ item }} dest=/etc/nginx/sites-enabled/{{ item }} state=link
  with_items:
    - front
    - api
  notify: "restart nginx"
