---
- name: Remove Apache2
  become: yes
  apt: name=apache2 state=absent

- name: Add the Nginx official repository
  apt_repository:
    repo: "deb http://nginx.org/packages/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} nginx"
    state: present
  when: ansible_os_family == "Debian"

- name: Install Nginx
  become: yes
  apt: pkg=nginx state=latest force=yes

- name: Configure Nginx to include the virtual hosts files
  become: yes
  lineinfile: dest=/etc/nginx/nginx.conf insertafter="include \/etc\/nginx\/conf\.d\/\*\.conf\;$" line="    include /etc/nginx/sites-enabled/*;"

- name: Create virtual hosts directories
  become: yes
  file: path=/etc/nginx/{{ item }} state=directory mode=0755
  with_items:
    - sites-available
    - sites-enabled
