---

- name: Remove Apache2
  package: name=apache2 state=absent

- name: Add the Nginx official repository
  apt_repository:
    repo: "deb http://nginx.org/packages/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} nginx"
    state: present
  when: ansible_os_family == "Debian"

- name: Install Nginx
  package: name=nginx state=latest

- name: Configure Nginx to include the virtual hosts files
  lineinfile:
    dest: /etc/nginx/nginx.conf
    insertafter: "include \/etc\/nginx\/conf\.d\/\*\.conf\;$"
    line: "    include /etc/nginx/sites-enabled/*;"
  notify: restart nginx

- name: Create virtual hosts directories
  file: path=/etc/nginx/{{ item }} state=directory mode=0755
  with_items:
    - sites-available
    - sites-enabled
  notify: restart nginx
