---

- name: Provide a default Nginx template for the Node HTTP apps
  set_fact:
    apps_node: |
      {{ apps_node|combine({item.key: {'nginx_template': role_path~'/templates/node_http.tpl'}}, recursive=true) }}
  with_dict: "{{ apps_node }}"
  when: not item.value.https|default(false) and item.value.nginx_template is not defined

- name: Provide a default Nginx template for the Node HTTPS apps
  set_fact:
    apps_node: |
      {{ apps_node|combine({item.key: {'nginx_template': role_path~'/templates/node_https.tpl'}}, recursive=true) }}
  with_dict: "{{ apps_node }}"
  when: item.value.https|default(false) and item.value.nginx_template is not defined

- name: Provide the basic config for the Node apps
  include_role:
    name: apps
  vars:
    apps: "{{ apps_node }}"

- name: Create the "node" user, under which the Node apps will run
  user: name=node

- name: Ensure Forever is installed
  npm: name=forever global=yes

- name: Configure the Node apps to start at the system boot
  template: src=node_app_run.conf.tpl dest=/etc/init/{{ app.value.name }}-run.conf mode=0644
  with_dict: "{{ apps_node }}"

- name: Provide a default Nginx template for the Front-end HTTP apps
  set_fact:
    apps_front: |
      {{ apps_front|combine({item.key: {'nginx_template': role_path~'/templates/front_http.tpl'}}, recursive=true) }}
  with_dict: "{{ apps_front }}"
  when: not item.value.https|default(false) and item.value.nginx_template is not defined

- name: Provide a default Nginx template for the Front-end HTTPS apps
  set_fact:
    apps_front: |
      {{ apps_front|combine({item.key: {'nginx_template': role_path~'/templates/front_https.tpl'}}, recursive=true) }}
  with_dict: "{{ apps_front }}"
  when: item.value.https|default(false) and item.value.nginx_template is not defined

- name: Provide the basic config for the Front-end apps
  include_role:
    name: apps
  vars:
    apps: "{{ apps_front }}"
