---

- name: Set up the server with a PHP application
  hosts: localhost

  become: yes
  become_user: root
  become_method: sudo

  vars_files:
    - vars/php.yml

  roles:
    - server
    - mysql
    - php
    - nginx
    - nginx_https
    - samba
    - composer
    - apps_php
    # - local_deploy
