---

- name: Install Samba
  package: name=samba state=latest

- name: Add the Samba user
  shell: (echo '{{ samba.password }}'; echo '{{ samba.password }}') | smbpasswd -s -a {{ samba.user }}

- name: Configure Samba
  template: src=smb.conf.tpl dest=/etc/samba/smb.conf

- name: Ensure Samba is started
  service: name=smbd state=started
