---
- name: Install Samba
  apt: pkg=samba state=installed

- name: Add the Samba user
  shell: sudo echo -e "{{ samba.password }}\n{{ samba.password }}" | sudo smbpasswd -s -a vagrant

- name: Configure Samba
  become: yes
  template: src=smb.conf.tpl dest=/etc/samba/smb.conf

- name: Ensure Samba is started
  service: name=smbd state=started
