---
- name: Configure the virtual hosts for the defined applications
  become: yes
  template: src=nginx/app.tpl dest=/etc/nginx/sites-available/{{ item.value.name }}
  with_dict: "{{ apps }}"

- name: Enabled the configured virtual hosts
  become: yes
  file: src=/etc/nginx/sites-available/{{ item.value.name }} dest=/etc/nginx/sites-enabled/{{ item.value.name }} state=link
  with_dict: "{{ apps }}"
  notify: "restart nginx"
