---
- shell: hostname
  register: current_hostname

- name: Install MySQL
  become: yes
  apt: pkg={{ item }} state=latest force=yes
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb

- name: Update MySQL root password
  mysql_user: name=root host={{ item }} check_implicit_admin=yes password={{ mysql.root_password }} login_user=root login_password={{ mysql.root_password }}
  with_items:
    - "{{ current_hostname.stdout | lower }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Erase anonymous users
  mysql_user: name='' host={{ item }} state=absent login_user=root login_password={{ mysql.root_password }}
  with_items:
    - localhost
    - "{{ current_hostname.stdout | lower }}"

- name: Create databases for all applications
  mysql_db: name={{ item.value.mysql_database }} state=present login_user=root login_password={{ mysql.root_password }}
  with_dict: "{{ apps }}"

- name: Create MySQL users for all applications
  mysql_user: name={{ item.value.mysql_user }} password={{ item.value.mysql_password }} priv={{ item.value.mysql_database }}.*:ALL state=present login_user=root login_password={{ mysql.root_password }}
  with_dict: "{{ apps }}"

- name: Update the MySQL configuration file
  template: src=my.cnf.tpl dest=/etc/mysql/my.cnf
