---
- name: Install Symfony apps
  command: chdir="/var/www" creates="/var/www/{{ item.value.root_dir }}" symfony new {{ item.value.root_dir }} {{ item.value.symfony_version }}
  with_dict: "{{ apps }}"


- name: Configure the Symfony apps databases
  lineinfile: >
    dest="/var/www/{{ item.value.root_dir }}/app/config/parameters.yml"
    regexp="database_name:"
    line="    database_name: '{{ item.value.mysql_database }}'"
  with_dict: "{{ apps }}"


- name: Configure the Symfony apps database users
  lineinfile: >
    dest="/var/www/{{ item.value.root_dir }}/app/config/parameters.yml"
    regexp="database_user:"
    line="    database_user: '{{ item.value.mysql_user }}'"
  with_dict: "{{ apps }}"


- name: Configure the Symfony apps database user passwords
  lineinfile: >
    dest="/var/www/{{ item.value.root_dir }}/app/config/parameters.yml"
    regexp="database_password:"
    line="    database_password: '{{ item.value.mysql_password }}'"
  with_dict: "{{ apps }}"


- name: Set permissions on the app directories
  become: yes
  file: path="/var/www/{{ item.value.root_dir }}" owner="www-data" state="directory" recurse="yes"
  with_dict: "{{ apps }}"
