---
- name: Create directories for the Symfony apps
  become: yes
  file: path="{{ item.value.parent_path}}/{{ item.value.root_dir }}" state=directory owner=vagrant group=vagrant mode=0745 recurse=yes
  with_dict: "{{ apps }}"

- name: Install Symfony apps
  command: chdir="{{ item.value.parent_path }}" symfony new {{ item.value.root_dir }} {{ item.value.symfony_version }}
  with_dict: "{{ apps }}"

- name: Configure the Symfony apps databases
  lineinfile: >
    dest="{{ item.value.parent_path }}/{{ item.value.root_dir }}/app/config/parameters.yml"
    regexp="database_name:"
    line="    database_name: '{{ item.value.mysql_database }}'"
  with_dict: "{{ apps }}"

- name: Configure the Symfony apps database users
  lineinfile: >
    dest="{{ item.value.parent_path }}/{{ item.value.root_dir }}/app/config/parameters.yml"
    regexp="database_user:"
    line="    database_user: '{{ item.value.mysql_user }}'"
  with_dict: "{{ apps }}"

- name: Configure the Symfony apps database user passwords
  lineinfile: >
    dest="{{ item.value.parent_path }}/{{ item.value.root_dir }}/app/config/parameters.yml"
    regexp="database_password:"
    line="    database_password: '{{ item.value.mysql_password }}'"
  with_dict: "{{ apps }}"

- name: Install the permission fixer script in the applications
  template: src="permissions.sh.sf{{ item.value.symfony_version|int }}.tpl" path="{{ item.value.parent_path}}/{{ item.value.root_dir }}/permissions.sh" owner=vagrant group=vagrant mode=0744
  with_dict: "{{ apps }}"

- name: Run the permission fixer scripts
  become: yes
  shell: "{{ item.value.parent_path}}/{{ item.value.root_dir }}/permissions.sh"
  with_dict: "{{ apps }}"
