Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-16.04"

  config.vm.hostname = "symfony"
  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "symfony"
    vb.memory = "2048"
  end

  # Deploy the base Ansible roles on the machine.
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "deploy_roles.yml"
    ansible.limit = "localhost"
    ansible.inventory_path = "inventories/hosts"
  end

  # Provision the machine.
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "setup_symfony3.yml"
    ansible.limit = "localhost"
    ansible.inventory_path = "inventories/hosts"
  end
end
