---

- name: Provide a default Nginx template for the PHP HTTP apps
  set_fact:
    apps_php: |
      {{ apps_php|combine({item.key: {'nginx_template': role_path~'/templates/app_http.tpl'}}, recursive=true) }}
  with_dict: "{{ apps_php }}"
  when: not item.value.https|default(false) and item.value.nginx_template is not defined

- name: Provide a default Nginx template for the PHP HTTPS apps
  set_fact:
    apps_php: |
      {{ apps_php|combine({item.key: {'nginx_template': role_path~'/templates/app_https.tpl'}}, recursive=true) }}
  with_dict: "{{ apps_php }}"
  when: item.value.https|default(false) and item.value.nginx_template is not defined

- name: Provide the basic config for the apps
  include_role:
    name: apps
  vars:
    apps: "{{ apps_php }}"

- name: Install the fresh PHP apps
  include: app.yml
  with_dict: "{{ apps_php }}"
  when: app.value.new|default(false)
  loop_control:
    loop_var: app
