---

- name: Install MySQL
  package: name={{ item }} state=latest
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb

- shell: hostname
  register: current_hostname

- name: Update MySQL root password
  mysql_user: name=root host={{ item }} check_implicit_admin=yes password={{ mysql.root_password }}
  with_items:
    - "{{ current_hostname.stdout|lower }}"
    - 127.0.0.1
    - ::1
    - localhost
  ignore_errors: true

- name: Erase anonymous users
  mysql_user: name='' host={{ item }} state=absent login_user=root login_password={{ mysql.root_password }}
  with_items:
    - localhost
    - "{{ current_hostname.stdout|lower }}"

- name: Update the MySQL config
  ini_file:
    path: /etc/mysql/my.cnf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items: "{{ mysql.cnf_values }}"
  when: mysql.cnf_values is defined
  notify: restart mysql
