---
- name: Install base system packages
  become: yes
  apt: pkg={{ item }} state=latest
  with_items: "{{ server.packages }}"

- name: Set the timezone
  become: yes
  file: src=timezone.tpl dest=/etc/timezone

- name: Set the localtime
  become: yes
  file: src=/usr/share/zoneinfo/{{ server.timezone }} dest=/etc/localtime state=link force=yes backup=yes

- name: Set default system language pack
  shell: locale-gen {{ server.locale }}
  become: yes

- name: Add the Nginx official repository
  apt_repository: repo="deb http://nginx.org/packages/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} nginx" state=present
  when: ansible_os_family == "Debian"
  
- name: Add the official MySQL 5.6 repository
  apt_repository: repo="deb http://repo.mysql.com/apt/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} mysql-5.6" state=present
  when: ansible_os_family == "Debian"

- name: Add PHP repository for Ubuntu
  apt_repository: repo="{{ php_conf.repository }}" state=present
  when: ansible_distribution == "Ubuntu"

- name: Update packages cache
  apt: update_cache=yes
