---

- include_tasks: https.yml
  when: app.value.https|default(false)

- include_tasks: nginx.yml

- include_tasks: mysql.yml
  when: app.value.mysql_database is defined and app.value.mysql_user is defined and app.value.mysql_password is defined

- name: Create the app root dir
  file:
    path: "{{ app.value.path }}"
    state: directory
    owner: "{{ app.value.owner|default(ansible_ssh_user) }}"
    group: "{{ app.value.group|default(ansible_ssh_user) }}"
    mode: 0745
    recurse: yes
