---

- block:
    - name: Fetch Node.JS configuration script
      get_url: url={{ _node_debian_repos[node.version] }} dest=/tmp/install-nodejs mode=0744 force=yes

    - name: Run Node.JS configuration script
      shell: /tmp/install-nodejs

    - name: Remove Node.JS configuration script
      file: path=/tmp/install-nodejs state=absent
  when: ansible_os_family == "Debian"

- name: Install Node.JS
  package: name=nodejs state=latest

- name: Install Node.JS global packages
  npm: name={{ item }} global=yes
  with_items: "{{ node.global_packages|default([]) }}"

- block:
    - block:
        - name: Add Yarn APT key
          apt_key: url=https://dl.yarnpkg.com/debian/pubkey.gpg

        - name: Add Yarn APT source
          lineinfile:
            path: /etc/apt/sources.list.d/yarn.list
            line: "deb https://dl.yarnpkg.com/debian/ stable main"
            create: yes

        - name: Update APT cache
          apt: update_cache=yes
      when: ansible_os_family == "Debian"

    - name: Install Yarn
      package: name=yarn state=present
  when: node.yarn|default(false)
