---

- name: Install the barebone Symfony app
  command: symfony new symfony_tmp {{ app.value.symfony_version }} && cp -R /symfony_tmp /. && rm -rf /symfony_tmp
  args:
    chdir: "{{ app.value.path }}"
    creates: "{{ app.value.path }}/app"

- name: Configure the app database parameters
  lineinfile: dest={{ app.value.path }}/app/config/parameters.yml regexp={{ item.regexp }} line={{ item.line }}
  with_items:
    - {regexp: "database_name:", line: "    database_name: '{{ app.value.mysql_database }}'"}
    - {regexp: "database_user:", line: "    database_user: '{{ app.value.mysql_user }}'"}
    - {regexp: "database_password:", line: "    database_password: '{{ app.value.mysql_password }}'"}

- name: Set permissions for the web user on writable resources
  acl:
    path: "{{ app.value.path }}/{{ item[0] }}"
    etype: user
    entity: "{{ php_fpm.user }}"
    permissions: rwx
    default: "{{ item[1] }}"
    recursive: yes
    state: present
  with_nested:
    - [var/cache, var/logs, web/bundles]
    - [yes, no]

- name: Set permissions masks on writable resources
  acl:
    path: "{{ app.value.path }}/{{ item }}"
    etype: mask
    permissions: rwx
    default: yes
    recursive: yes
    state: present
  with_items: [var/cache, var/logs, web/bundles]
