---

- name: Install the barebone Symfony app
  shell: "composer create-project symfony/website-skeleton symfony_tmp && cp -r symfony_tmp/. ./ && rm -rf symfony_tmp"
  args:
    chdir: "{{ app.value.path }}"
    creates: "{{ app.value.path }}/config"

- set_fact:
    _apps_symfony_env_vars:
      APP_ENV: dev
      APP_DEBUG: 1
      DATABASE_URL: "mysql://{{ app.value.mysql_user }}:{{ app.value.mysql_password }}@127.0.0.1:3306/{{ app.value.mysql_database }}"

- name: Install the FastCGI params file
  template: src=sf4_fastcgi_params.tpl dest=/etc/nginx/{{ app.key }}_params

- name: Configure environment variables for CLI
  lineinfile: path=/etc/environment regexp="^{{ item.key }}=" line="{{ item.key }}=\"{{ item.value }}\""
  with_dict: "{{ _apps_symfony_env_vars }}"

- name: Restart Nginx
  service: name=nginx state=restarted
