---

- name: Install the barebone Symfony app
  shell: "composer create-project symfony/website-skeleton symfony_tmp && cp -r symfony_tmp/. ./ && rm -rf symfony_tmp"
  args:
    chdir: "{{ app.value.path }}"
    creates: "{{ app.value.path }}/config"
