---

- name: Install the barebone Symfony app
  shell: "composer create-project symfony/website-skeleton symfony_tmp && cp -r symfony_tmp/. ./ && rm -rf symfony_tmp"
  args:
    chdir: "{{ app.value.path }}"
    creates: "{{ app.value.path }}/config"

- name: Install the CLI & FastCGI params files
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - {src: sf4_cli_params.tpl, dest: "/etc/profile.d/{{ app.key }}_params.sh"}
    - {src: sf4_fastcgi_params.tpl, dest: "/etc/nginx/{{ app.key }}_params"}

- name: Restart Nginx
  service: name=nginx state=restarted
