---

- name: Set up the server with a Symfony 4 project
  hosts: localhost
  become: yes

  vars_files:
    - vars/common.yml

  roles:
    - server
    - mysql
    - php
    - node
    - nginx
    - nginx_https
    - samba
    - composer
    - apps_symfony
    # - local_deploy
