---

- name: PHP CLI - set timezone & enable OPcache
  ini_file:
    path: "{{ php_conf.conf_path }}/cli/php.ini"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - {section: Date, option: date.timezone, value: "{{ server.timezone }}"}
    - {section: opcache, option: opcache.enable_cli, value: 1}

- name: PHP CLI - set php.ini directives
  ini_file:
    path: "{{ php_conf.conf_path }}/cli/php.ini"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items: "{{ php.ini_values.common|default([]) + php.ini_values.cli|default([]) }}"
  when: php.ini_values is defined

- name: PHP CLI - enable PECL extensions
  file:
    src: "{{ php_conf.conf_path }}/mods-available/{{ item }}.ini"
    dest: "{{ php_conf.conf_path }}/cli/conf.d/{{ item }}.ini"
    state: link
  with_items: "{{ php.pecl_extensions }}"
