---
- name: PHP CLI - set timezone
  lineinfile:
    dest: {{ php_conf.conf_path }}/cli/php.ini
    regexp: "date.timezone ="
    line: "date.timezone = {{ server.timezone }}"

- name: PHP CLI - enable OPCACHE
  lineinfile: dest={{ php_conf.conf_path }}/cli/php.ini regexp=";?opcache.enable_cli=\d" line="opcache.enable_cli=1"

- name: PHP CLI - enable PECL extensions
  file:
    src: {{ php_conf.conf_path }}/mods-available/{{ item }}.ini
    dest: {{ php_conf.conf_path }}/cli/conf.d/{{ item }}.ini
    state: link
  with_items: "{{ php.pecl_extensions }}"
