---

- name: PHP FPM - set socket owner, group and mode
  lineinfile:
    dest: "{{ php_conf.conf_path }}/fpm/pool.d/www.conf"
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {regexp: "^;?listen.owner", line: "listen.owner = {{ php_fpm.listen_owner }}"}
    - {regexp: "^;?listen.group", line: "listen.group = {{ php_fpm.listen_group }}"}
    - {regexp: "^;?listen.mode", line: "listen.mode = 0660"}
  notify: restart php-fpm

- name: PHP FPM - set timezone
  lineinfile:
    dest: "{{ php_conf.conf_path }}/fpm/php.ini"
    regexp: "date.timezone ="
    line: "date.timezone = {{ server.timezone }}"
  notify: restart php-fpm

- name: PHP FPM - enable OPcache
  lineinfile: dest={{ php_conf.conf_path }}/fpm/php.ini regexp=";?opcache.enable=\d" line="opcache.enable=1"
  notify: restart php-fpm

- name: PHP FPM - enable PECL extensions
  file:
    src: "{{ php_conf.conf_path }}/mods-available/{{ item }}.ini"
    dest: "{{ php_conf.conf_path }}/fpm/conf.d/{{ item }}.ini"
    state: link
  with_items: "{{ php.pecl_extensions }}"
  notify: restart php-fpm
