---

- name: PHP FPM - set socket owner, group and mode
  ini_file:
    path: "{{ php_conf.conf_path }}/fpm/pool.d/www.conf"
    section: www
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - {option: listen.owner, value: "{{ php_fpm.listen_owner }}"}
    - {option: listen.group, value: "{{ php_fpm.listen_group }}"}
    - {option: listen.mode, value: 0660}
  notify: restart php-fpm

- name: PHP FPM - set timezone & enable OPcache
  ini_file:
    path: "{{ php_conf.conf_path }}/fpm/php.ini"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - {section: Date, option: date.timezone, value: "{{ server.timezone }}"}
    - {section: opcache, option: opcache.enable, value: 1}
  notify: restart php-fpm

- name: PHP FPM - enable PECL extensions
  file:
    src: "{{ php_conf.conf_path }}/mods-available/{{ item }}.ini"
    dest: "{{ php_conf.conf_path }}/fpm/conf.d/{{ item }}.ini"
    state: link
  with_items: "{{ php.pecl_extensions }}"
  notify: restart php-fpm
