---

- name: Add PHP repository for Ubuntu
  apt_repository: repo={{ php_conf.repository }} state=present
  when: ansible_os_family == "Debian"

- name: Install PHP
  package: name={{ php_conf.package }} state=latest

- name: Install PHP FPM
  package: name={{ php_conf.fpm_package }} state=latest

- name: Install PHP CLI
  package: name={{ php_conf.cli_package }} state=latest

- name: Install PHP extensions
  package: name={{ item }} state=latest
  with_items: "{{ php.extensions }}"

- name: Install PHP tools needed for adding PECL extensions
  package: name={{ item }} state=latest
  with_items: "{{ php_conf.pecl_packages }}"

- name: Install PHP extensions via PECL
  shell: "pecl install {{ item }}"
  with_items: "{{ php.pecl_extensions }}"

- name: Install Xdebug if demanded
  package: name=php-xdebug state=latest
  when: php.xdebug|default(false)
