---

- name: Register PHP configuration
  set_fact:
    php_conf: "{{ _php_conf_dict[php.version] }}"

- name: Install PHP
  import_tasks: install.yml

- name: Configure PHP
  import_tasks: configure.yml
