---

- name: Create SSL certs directory
  file: path=/etc/nginx/ssl state=directory owner=root group=root mode=0600

- name: Avoid old cipher suites
  blockinfile:
    dest: /etc/nginx/nginx.conf
    insertbefore: "^}$"
    content: |
          ssl_prefer_server_ciphers on;
          ssl_ciphers EECDH+CHACHA20:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5;
  notify: restart nginx

- name: Generate strong DHE key
  command: openssl dhparam -out /etc/nginx/ssl/dhparam.pem 2048 creates=/etc/nginx/ssl/dhparam.pem

- name: Change permissions for the DHE key
  file: path=/etc/nginx/ssl/dhparam.pem owner=root group=root mode=0600

- name: Enable TLS session resumption
  blockinfile:
    dest: /etc/nginx/nginx.conf
    insertbefore: "^}$"
    content: |
          ssl_session_cache shared:SSL:5m;
          ssl_session_timeout 1h;
  notify: restart nginx
