---
- name: Remove Apache2
  become: yes
  apt: name=apache2 state=absent

- name: Install Nginx
  become: yes
  apt: pkg=nginx state=latest force=yes

- name: Configure Nginx to include the virtual hosts files
  become: yes
  lineinfile: dest=/etc/nginx/nginx.conf insertafter="include \/etc\/nginx\/conf\.d\/\*\.conf\;$" line="    include /etc/nginx/sites-enabled/*;"

- name: Create virtual hosts directories
  become: yes
  file: path=/etc/nginx/{{ item }} state=directory mode=0755
  with_items:
    - sites-available
    - sites-enabled

- name: Configure the virtual hosts for the defined applications
  become: yes
  template: src=app.tpl dest=/etc/nginx/sites-available/{{ item.value.name }}
  with_dict: "{{ apps }}"

- name: Enabled the configured virtual hosts
  become: yes
  file: src=/etc/nginx/sites-available/{{ item.value.name }} dest=/etc/nginx/sites-enabled/{{ item.value.name }} state=link
  with_dict: "{{ apps }}"
  notify: "restart nginx"
